/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package io.github.kildot.backgroundRemover;

/**
 *
 * @author Dominik
 */
public class ToolbarPanel extends java.awt.Panel implements Params.Listener {

    Params globalParams;

    /**
     * Creates new form ToolbarPanel
     */
    public ToolbarPanel(Params params) {
        globalParams = params;
        initComponents();
        globalParams.addListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionTypeGroup = new javax.swing.ButtonGroup();
        pointsSelection = new javax.swing.JToggleButton();
        noiseSelection = new javax.swing.JToggleButton();
        sumSelection = new javax.swing.JToggleButton();

        selectionTypeGroup.add(pointsSelection);
        pointsSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/kildot/backgroundRemover/res/Point.png"))); // NOI18N
        pointsSelection.setText("Points selection");
        pointsSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsSelectionparamActionPerformed(evt);
            }
        });
        add(pointsSelection);

        selectionTypeGroup.add(noiseSelection);
        noiseSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/kildot/backgroundRemover/res/Noise.png"))); // NOI18N
        noiseSelection.setSelected(true);
        noiseSelection.setText("Noise selection");
        noiseSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noiseSelectionparamActionPerformed(evt);
            }
        });
        add(noiseSelection);

        selectionTypeGroup.add(sumSelection);
        sumSelection.setText("Sum selection");
        sumSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumSelectionparamActionPerformed(evt);
            }
        });
        add(sumSelection);
    }// </editor-fold>//GEN-END:initComponents

    private void pointsSelectionparamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsSelectionparamActionPerformed
        updateState();
    }//GEN-LAST:event_pointsSelectionparamActionPerformed

    private void noiseSelectionparamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noiseSelectionparamActionPerformed
        updateState();
    }//GEN-LAST:event_noiseSelectionparamActionPerformed

    private void sumSelectionparamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumSelectionparamActionPerformed
        updateState();
    }//GEN-LAST:event_sumSelectionparamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton noiseSelection;
    private javax.swing.JToggleButton pointsSelection;
    private javax.swing.ButtonGroup selectionTypeGroup;
    private javax.swing.JToggleButton sumSelection;
    // End of variables declaration//GEN-END:variables

    void updateState() {
        Params copy = globalParams.copy();
        copy.selectType =
            noiseSelection.isSelected() ? Params.SELECT_NOISE :
            sumSelection.isSelected() ? Params.SELECT_SUM : Params.SELECT_POINTS;
        globalParams.set(copy, false, this);
    }

    @Override
    public void parametersChanged(long fields, boolean self) {
        if (!self && (fields & Params.SELECT_TYPE) != 0) {
            noiseSelection.setSelected(globalParams.selectType == Params.SELECT_NOISE);
            pointsSelection.setSelected(globalParams.selectType == Params.SELECT_POINTS);
            sumSelection.setSelected(globalParams.selectType == Params.SELECT_SUM);
        }
    }

    @Override
    public void eventTriggered(Params.EventData event) {
    }
}
